name: Node Tests

on: [push]

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['22', '24']
    name: Node ${{ matrix.node }}

    steps:
    - uses: actions/checkout@v4
    - run: yarn install --frozen-lockfile
    - run: yarn lint
    - run: yarn test
